server:
  port: 8081
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: covid_tracker
    password: B+LL6udNcoYkiJNPIvf0y0bx/t32doaULEh9AUJNA14=
    url: jdbc:mysql://localhost:3306/covid19tracker
  mvc:
    servlet:
      path: /api/v1/
#aws:
#  accessKey: AKIATDHGKMHMU7KZWOVP
#  secretKey: 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
